### ISSUE TITLE
GPU lacks support; bad display

### ISSUE THREAD

**Issue by tylerdq** [ShenMian/sokoban-rs#12]
When I try to run the program I get this:

```
[2m2024-11-16T16:29:03.699578Z[0m [32m INFO[0m [2mbevy_diagnostic::system_information_diagnostics_plugin::internal[0m[2m:[0m SystemInfo { os: "Linux  KISS Linux Community", kernel: "6.6.59_1", cpu: "Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz", core_count: "4", memory: "7.5 GiB" }
[2m2024-11-16T16:29:03.761181Z[0m [32m INFO[0m [2mbevy_render::renderer[0m[2m:[0m AdapterInfo { name: "Mesa Intel(R) UHD Graphics 620 (KBL GT2)", vendor: 32902, device: 0, device_type: IntegratedGpu, driver: "OpenGL", driver_info: "4.6 (Compatibility Profile) Mesa 24.2.5", backend: Gl }
[2m2024-11-16T16:29:03.999375Z[0m [33m WARN[0m [2mbevy_pbr::ssao[0m[2m:[0m ScreenSpaceAmbientOcclusionPlugin not loaded. GPU lacks support: TextureFormat::R16Float does not support TextureUsages::STORAGE_BINDING.
[2m2024-11-16T16:29:03.999632Z[0m [32m INFO[0m [2mbevy_winit::system[0m[2m:[0m Creating new window "Sokoban" (Entity { index: 0, generation: 1 })
[2m2024-11-16T16:29:04.008904Z[0m [32m INFO[0m [2msoukoban_rs::systems::level[0m[2m:[0m Loading levels from files
[2m2024-11-16T16:29:04.008956Z[0m [32m INFO[0m [2msoukoban_rs::systems::level[0m[2m:[0m   "assets/levels/box_world_100.xsb"
[2m2024-11-16T16:29:04.018983Z[0m [32m INFO[0m [2msoukoban_rs::systems::level[0m[2m:[0m   "assets/levels/microban_155.xsb"
[2m2024-11-16T16:29:04.033492Z[0m [32m INFO[0m [2msoukoban_rs::systems::level[0m[2m:[0m   "assets/levels/microban_II_135.xsb"
[2m2024-11-16T16:29:04.049912Z[0m [32m INFO[0m [2msoukoban_rs::systems::level[0m[2m:[0m Done
thread 'Compute Task Pool (1)' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:296:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
Encountered a panic in system `bevy_render::view::window::create_surfaces`!
thread 'Compute Task Pool (1)' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:296:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
Encountered a panic in system `bevy_render::render_asset::prepare_assets<bevy_render::texture::image::GpuImage>`!
thread 'Compute Task Pool (1)' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:296:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
Encountered a panic in system `bevy_pbr::render::light::prepare_lights`!
thread 'Compute Task Pool (3)' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:296:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
Encountered a panic in system `bevy_render::render_asset::prepare_assets<bevy_sprite::mesh2d::material::PreparedMaterial2d<bevy_sprite::mesh2d::color_material::ColorMaterial>>`!
thread 'Compute Task Pool (1)' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:296:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
Encountered a panic in system `bevy_render::render_asset::prepare_assets<bevy_pbr::material::PreparedMaterial<bevy_pbr::pbr_material::StandardMaterial>>`!
thread 'Compute Task Pool (2)' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:296:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
Encountered a panic in system `bevy_render::globals::prepare_globals_bufferthread '`!
Compute Task Pool (0)' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:296:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
thread 'Encountered a panic in system `mainbevy_pbr::render::skin::prepare_skins' panicked at `!
/home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:296:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
thread 'Compute Task Pool (1)' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:Encountered a panic in system `296bevy_pbr::ssr::prepare_ssr_settings:`!
14:
called `Result::unwrap()` on an `Err` value: BadDisplay
Encountered a panic in system `bevy_pbr::render::fog::prepare_fog`!
thread 'Compute Task Pool (3)' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:296:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
Encountered a panic in system `bevy_render::view::prepare_view_uniforms`!
thread 'Compute Task Pool (0)' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:296:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
Encountered a panic in system `bevy_pbr::light_probe::upload_light_probes`!
thread 'Compute Task Pool (2)' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:296:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
Encountered a panic in system `bevy_pbr::cluster::prepare_clusters`!
thread 'Compute Task Pool (2)' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:296:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
Encountered a panic in system `bevy_render::view::visibility::range::write_render_visibility_ranges`!
thread 'Compute Task Pool (2)' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:296:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
Encountered a panic in system `bevy_sprite::render::prepare_sprite_image_bind_groups`!
thread '<unnamed>' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.21.1/src/gles/egl.rs:296:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
Encountered a panic in system `bevy_render::renderer::render_system`!
```

Is there something I can do when I build to enable support for my GPU? Or perhaps disable ambient occlusion?

**Comment by ShenMian** [comment]
This is a [Bevy](https://github.com/bevyengine/bevy) related issue, which is the game engine used in this project.

1. From the terminal output, it can be seen that SSAO is automatically disabled after detecting GPU incompatibility (`...Plugin not loaded`).
2. The subsequent error (BadDisplay) comes from the dependency (`wgpu` from `bevy`) and is no longer within the scope of this project.

I don't know how to solve this problem either, sorry. 😢

**Comment by tylerdq** [comment]
Thank you so much for clarifying this and pointing me in the right direction!
